// Generates the static data the scenes need (geo outlines, brand logo paths) and vendors the
// fonts, so the page itself never depends on node_modules at render time.
// Run once after `npm install`: node tools/build-assets.mjs
import { readFileSync, writeFileSync, copyFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const require = createRequire(import.meta.url)
const topojson = require('topojson-client')
const d3 = require('d3-geo')
const root = join(dirname(fileURLToPath(import.meta.url)), '..')

// --- Geo -------------------------------------------------------------------------------------
// Centroid box around Africa catches Middle-East and Mediterranean countries too; drop them by name.
const NOT_AFRICA = new Set(['Yemen', 'Saint Helena', 'United Arab Emirates', 'Syria', 'Saudi Arabia', 'Qatar', 'Oman',
  'Malta', 'Lebanon', 'Kuwait', 'Jordan', 'Israel', 'Palestine', 'Iraq', 'Iran', 'N. Cyprus', 'Cyprus', 'Bahrain'])
const roundCoord = (point) => [Math.round(point[0] * 100) / 100, Math.round(point[1] * 100) / 100]
const polygonsOf = (geometry) => (geometry.type === 'Polygon' ? [geometry.coordinates] : geometry.coordinates)

const countries50m = require('world-atlas/countries-50m.json')
const countryFeatures = topojson.feature(countries50m, countries50m.objects.countries).features
const africa = countryFeatures
  .filter((feature) => {
    const [lon, lat] = d3.geoCentroid(feature)
    return lon > -27 && lon < 60 && lat > -42 && lat < 38 && !NOT_AFRICA.has(feature.properties.name)
  })
  .map((feature) => ({
    name: feature.properties.name,
    // Each polygon is [outerRing, ...holes]; each ring is [[lon, lat], ...]
    polygons: polygonsOf(feature.geometry).map((polygon) => polygon.map((ring) => ring.map(roundCoord))),
  }))

const land110m = require('world-atlas/land-110m.json')
const worldLand = topojson.feature(land110m, land110m.objects.land).features
  .flatMap((feature) => polygonsOf(feature.geometry))
  .map((polygon) => polygon.map((ring) => ring.map(roundCoord)))

const geo = {
  africa,
  worldLand,
  cities: {
    kigali: [30.0619, -1.9441],
    capeTown: [18.4241, -33.9249],
  },
}
writeFileSync(join(root, 'src/data/geo.js'),
  '// Generated by tools/build-assets.mjs from Natural Earth (world-atlas). Do not edit by hand.\n' +
  `window.SC_GEO = ${JSON.stringify(geo)};\n`)
console.log(`geo: ${africa.length} African countries, ${worldLand.length} world land polygons`)

// --- Logo ------------------------------------------------------------------------------------
// Pull the real brand paths out of the docs logo so the lockup is pixel-identical to the brand.
const logoSvg = readFileSync(join(root, '../logo/logo-dark.svg'), 'utf8')
const pathData = [...logoSvg.matchAll(/<path d="([^"]+)"/g)].map((match) => match[1])
// The docs logo is mark + "strettch cloud" wordmark + a "DOCS" badge (x >= 204). The badge is
// docs-site chrome, not the brand lockup, so it is deliberately left out.
const wordmark = pathData[3]

// Approximate bounding box of an absolute-command path (control points included — good enough
// for grouping subpaths into letters).
function boundingBox(path) {
  const xs = []
  const ys = []
  let command = null
  let pending = []
  for (const token of path.match(/[A-Za-z]|-?\d*\.?\d+(?:e-?\d+)?/g)) {
    if (/[A-Za-z]/.test(token)) { command = token; pending = []; continue }
    const value = Number(token)
    if (command === 'H') xs.push(value)
    else if (command === 'V') ys.push(value)
    else {
      pending.push(value)
      if (pending.length === 2) { xs.push(pending[0]); ys.push(pending[1]); pending = [] }
    }
  }
  return { x0: Math.min(...xs), x1: Math.max(...xs), y0: Math.min(...ys), y1: Math.max(...ys) }
}
// Split the wordmark into one path per letter: subpaths whose x-ranges overlap belong to the same
// glyph (a "t" is stem + crossbar, an "o" is outer ring + counter).
const subpaths = wordmark.match(/M[^M]*/g).map((d) => ({ d, box: boundingBox(d) }))
const glyphGroups = []
for (const subpath of subpaths) {
  const group = glyphGroups.find((candidate) => subpath.box.x0 < candidate.box.x1 - 0.5 && subpath.box.x1 > candidate.box.x0 + 0.5)
  if (group) {
    group.d += subpath.d
    group.box = { x0: Math.min(group.box.x0, subpath.box.x0), x1: Math.max(group.box.x1, subpath.box.x1), y0: Math.min(group.box.y0, subpath.box.y0), y1: Math.max(group.box.y1, subpath.box.y1) }
  } else {
    glyphGroups.push({ ...subpath, box: { ...subpath.box } })
  }
}
const WORDMARK_TEXT = 'strettchcloud'
if (glyphGroups.length !== WORDMARK_TEXT.length) throw new Error(`expected ${WORDMARK_TEXT.length} glyphs, found ${glyphGroups.length}`)
const letters = glyphGroups.map((group, index) => ({
  char: WORDMARK_TEXT[index],
  word: index < 8 ? 'strettch' : 'cloud',
  d: group.d,
  box: Object.fromEntries(Object.entries(group.box).map(([key, value]) => [key, Math.round(value * 100) / 100])),
}))

const logo = {
  // Mark + wordmark only (the wordmark ends at x≈186).
  viewBox: [0, 0, 186, 32],
  markSlabs: { bottom: pathData[0], middle: pathData[1], top: pathData[2] },
  wordmark,
  letters,
  colors: { mark: '#6B63FF', wordmark: '#FFFFFF' },
}
writeFileSync(join(root, 'src/data/logo.js'),
  '// Generated by tools/build-assets.mjs from ../logo/logo-dark.svg. Do not edit by hand.\n' +
  `window.SC_LOGO = ${JSON.stringify(logo)};\n`)
console.log(`logo: extracted mark + wordmark, split into ${letters.length} letters (${letters.map((letter) => letter.char).join('')})`)

// --- Fonts -----------------------------------------------------------------------------------
const fonts = [
  ['@fontsource-variable/inter/files/inter-latin-wght-normal.woff2', 'inter-var.woff2'],
  ['@fontsource-variable/space-grotesk/files/space-grotesk-latin-wght-normal.woff2', 'space-grotesk-var.woff2'],
  ['@fontsource-variable/jetbrains-mono/files/jetbrains-mono-latin-wght-normal.woff2', 'jetbrains-mono-var.woff2'],
  ['@fontsource/instrument-serif/files/instrument-serif-latin-400-normal.woff2', 'instrument-serif.woff2'],
  ['@fontsource/instrument-serif/files/instrument-serif-latin-400-italic.woff2', 'instrument-serif-italic.woff2'],
]
for (const [source, target] of fonts) copyFileSync(require.resolve(source), join(root, 'assets/fonts', target))
console.log(`fonts: vendored ${fonts.length} files`)
