// Generates src/data/rwanda-hires.js for s04-in-country from Natural Earth 10m (world-atlas):
//   ring    — Rwanda's outer border, unique points, flat [lon, lat, lon, lat, …] (5 decimals).
//   lattice — the neighbouring LAND outside Rwanda on a 0.025° grid (aligned with s03's 0.05°
//             LOD grid, which it contains, and with the 1° map grid), within MAX_DISTANCE of the
//             border: flat [i, j, d, …] with lon = lon0 + i·step, lat = lat0 − j·step and
//             d = distance to Rwanda's border in 0.001° (equirectangular, as the map projects).
// Run: node tools/build-rwanda.mjs
import { writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const require = createRequire(import.meta.url)
const topojson = require('topojson-client')
const root = join(dirname(fileURLToPath(import.meta.url)), '..')

const countries = require('world-atlas/countries-10m.json')
const land = require('world-atlas/land-10m.json')
const rwanda = topojson.feature(countries, countries.objects.countries).features.find((feature) => feature.properties.name === 'Rwanda')
if (rwanda.geometry.type !== 'Polygon' || rwanda.geometry.coordinates.length !== 1) throw new Error('expected Rwanda as one hole-free polygon')
const ring = rwanda.geometry.coordinates[0].slice(0, -1) // drop the closing duplicate
// Only land polygons that reach the lattice window (lon 26–34, lat −6…2) are tested.
const landPolygons = topojson.feature(land, land.objects.land).features
  .flatMap((feature) => (feature.geometry.type === 'Polygon' ? [feature.geometry.coordinates] : feature.geometry.coordinates))
  .filter((polygon) => polygon[0].some(([lon, lat]) => lon > 26 && lon < 34 && lat > -6 && lat < 2) ||
    (Math.min(...polygon[0].map((p) => p[0])) < 26 && Math.max(...polygon[0].map((p) => p[0])) > 34 &&
      Math.min(...polygon[0].map((p) => p[1])) < -6 && Math.max(...polygon[0].map((p) => p[1])) > 2))

function inRing([x, y], points) {
  let inside = false
  for (let i = 0, j = points.length - 1; i < points.length; j = i++) {
    const [xi, yi] = points[i]
    const [xj, yj] = points[j]
    if (yi > y !== yj > y && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) inside = !inside
  }
  return inside
}
const onLand = (point) => landPolygons.some((polygon) => inRing(point, polygon[0]) && !polygon.slice(1).some((hole) => inRing(point, hole)))
function distanceToRing([x, y]) {
  let best = Infinity
  for (let i = 0; i < ring.length; i++) {
    const [ax, ay] = ring[i]
    const [bx, by] = ring[(i + 1) % ring.length]
    const dx = bx - ax
    const dy = by - ay
    const k = Math.max(0, Math.min(1, ((x - ax) * dx + (y - ay) * dy) / (dx * dx + dy * dy || 1)))
    best = Math.min(best, Math.hypot(x - ax - k * dx, y - ay - k * dy))
  }
  return best
}

const STEP = 0.025
const LON0 = 27
const LAT0 = 1
const MAX_DISTANCE = 1.6
const cells = []
for (let j = 0; LAT0 - j * STEP >= -5; j++) {
  for (let i = 0; LON0 + i * STEP <= 33; i++) {
    const point = [Math.round((LON0 + i * STEP) * 1000) / 1000, Math.round((LAT0 - j * STEP) * 1000) / 1000]
    if (inRing(point, ring)) continue
    const distance = distanceToRing(point)
    if (distance > MAX_DISTANCE || !onLand(point)) continue
    cells.push(i, j, Math.round(distance * 1000))
  }
}

const data = {
  source: 'Natural Earth 1:10m via world-atlas/countries-10m.json + land-10m.json',
  ring: ring.flatMap(([lon, lat]) => [Math.round(lon * 1e5) / 1e5, Math.round(lat * 1e5) / 1e5]),
  lattice: { step: STEP, lon0: LON0, lat0: LAT0, cells },
}
writeFileSync(join(root, 'src/data/rwanda-hires.js'),
  '// Generated by tools/build-rwanda.mjs from Natural Earth 10m (world-atlas). Do not edit by hand.\n' +
  `window.SC_RWANDA_HIRES = ${JSON.stringify(data)};\n`)
console.log(`rwanda-hires: ${ring.length} border points, ${cells.length / 3} neighbour lattice points`)
